### ISSUE TITLE
Unhandled rejection SyntaxError: unknown: static is a reserved word in strict mode

### ISSUE THREAD

**Issue by djnaumov** [webpackmonitor/webpackmonitor#85] opened 2017-11-17 12:57 UTC
I got issue when I tried check-up your plugin.

So, I added this code in webpack.common.js
```
const WebpackMonitor = require('webpack-monitor');

// ...

plugins: [
  new WebpackMonitor({
    capture: true, // -> default 'true'
    target: '../monitor/myStatsStore.json', // default -> '../monitor/stats.json'
    launch: true, // -> default 'false'
    port: 3030, // default -> 8081
  }),
], 
```

then I run command npm start, I got error
```
Unhandled rejection SyntaxError: unknown: static is a reserved word in strict mode (109308:16)
  109306 |         function renderColorMask(input, buffer, caretPos) {
  109307 |             function handleStatic() {
> 109308 |                 static || null !== test.fn && void 0 !== testPos.input ? static && null !== test.fn && void 0 !== testPos.input && (static = !1,
         |                 ^
  109309 |                 maskTemplate += "</span>") : (static = !0, maskTemplate += "<span class='im-static''>");
  109310 |             }
  109311 |             if (void 0 !== colorMask) {
```
    node v8.9.1
    "webpack": "^3.8.1",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-dev-server": "^2.9.4",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "^4.1.1",
    "webpack-monitor": "^1.0.13"

**Comment by mbehzad** [comment] 2017-11-28 20:27
Hi @djnaumov, i think the issue is in the [Inputmask](https://github.com/RobinHerbots/Inputmask) library code that you pasted. and not from the webpack-monitor. The usage of the reserved word was fixed in a [PR](https://github.com/RobinHerbots/Inputmask/pull/1479).
you may want to update to a later version >v3.3.5.

**Closed as completed** 2018-03-28 12:47 UTC
